In [2]:
# Importing important libraries:
import os
import re
import pandas as pd

#stop words
stop_words=["a","the","able","about","data", "about", "above", "above", "across", "after", "afterwards", "again", 
            "against", "all", "almost", "alone", "along", "already", "also","although","always","am","among", "amongst",
            "amoungst", "amount",  "an", "and", "another", "any","anyhow","anyone","anything","anyway", "anywhere", 
            "are", "around", "as",  "at", "back","be","became", "because","become","becomes", "becoming", "been", 
            "before", "beforehand", "behind", "being", "below", "beside", "besides", "between", "beyond", "bill", 
            "both", "bottom","but", "by", "call", "can", "cannot", "cant", "co", "con", "could", "couldnt", "cry", 
            "de", "describe", "detail", "do", "done", "down", "due", "during", "each", "eg", "eight", "either", 
            "eleven","else", "elsewhere", "empty", "enough", "etc", "even", "ever", "every", "everyone", "everything",
            "everywhere", "except", "few", "fifteen", "fify", "fill", "find", "fire", "first", "five", "for", "former", 
            "formerly", "forty", "found", "four", "from", "front", "full", "further", "get", "give", "go", "had", "has", 
            "hasnt", "have", "he", "hence", "her", "here", "hereafter", "hereby", "herein", "hereupon", "hers", 
            "herself", "him", "himself", "his", "how", "however", "hundred", "ie", "if", "in", "inc", "indeed", 
            "interest", "into", "is", "it", "its", "itself", "keep", "last", "latter", "latterly", "least", "less", 
            "ltd", "made", "many", "may", "me", "meanwhile", "might", "mill", "mine", "more", "moreover", "most", 
            "mostly", "move", "much", "must", "my", "myself", "name", "namely", "neither", "never", "nevertheless", 
            "next", "nine", "no", "nobody", "none", "noone", "nor", "not", "nothing", "now", "nowhere", "of", "off", 
            "often", "on", "once", "one", "only", "onto", "or", "other", "others", "otherwise", "our", "ours", "ourselves",
            "out", "over", "own","part", "per", "perhaps", "please", "put", "rather", "re", "same", "see", "seem", 
            "seemed", "seeming", "seems", "serious", "several", "she", "should", "show", "side", "since", "sincere", "six",
            "sixty", "so", "some", "somehow", "someone", "something", "sometime", "sometimes", "somewhere", "still", 
            "such", "system", "take", "ten", "than", "that", "the", "their", "them", "themselves", "then", "thence", 
            "there", "thereafter", "thereby", "therefore", "therein", "thereupon", "these", "they", "thickv", "thin", 
            "third", "this", "those", "though", "three", "through", "throughout", "thru", "thus", "to", "together", "too",
            "top", "toward", "towards", "twelve", "twenty", "two", "un", "under", "until", "up", "upon", "us", "very", 
            "via", "was", "we", "well", "were", "what", "whatever", "when", "whence", "whenever", "where", "whereafter", 
            "whereas", "whereby", "wherein", "whereupon", "wherever", "whether", "which", "while", "whither", "who", 
            "whoever", "whole", "whom", "whose", "why", "will", "with", "within", "without", "would", "yet", "you", "your",
            "yours", "yourself", "yourselves", "the"]
  

In [3]:

#BUILDING A DICTIONARY of DIFFERENT WORDS APPEARING IN DOCUMENTS ALONG WITH WORD COUNTS:
all_classes = os.listdir("20_newsgroups")
print(all_classes)
# creating the word dictionary
word_dictionary = {}

"""
DICTIONARY :
    Keys   : words
    Values : count of word
"""

# using count for checking progress during runtime
count = 1

# Iterating through all classes
for class_ in all_classes:
    # storing the all documents in a list for a particular class
    all_docs = os.listdir("20_newsgroups"+"/"+class_)
    
    # traversing through all documents
    for docs in all_docs:
        
        # getting the base path which is common for all documents of a particular class
        path = "20_newsgroups"+"/"+class_+"/"+docs
        
        # opening the particular document as file object
        with open(path, encoding = "latin-1") as file_obj:
            
            # reading the document data
            file_data = file_obj.read()
            
            # stroing each words in a list , used re to remove the whitespaces 
            tokens = re.compile('\w+').findall(file_data)
            
            # traversing through all words and updating the value in dictionary if already exist otherwise will add to it
            for word in tokens:
                
                # checking if the word in a stop_word or not, is aphbetic and the lenth should be > 3 to avoid words like i, me etc
                if (word.lower() not in stop_words) and (word.lower().isalpha()) and (len(word.lower())>3):
                    
                    # getting the value of word from dictionary and increasing its count by 1 if word does not exists in dictionart then adding it with count 1
                    word_dictionary[word.lower()] = word_dictionary.get(word.lower(),0) + 1 
    # using print statement to check the progress during runtime
    print(count, "Class done")
    count+=1
    
'''Sorting the dictionary: '''     
sort_orders = sorted(word_dictionary.items(), key=lambda x: x[1], reverse=True)

''' Choosing the top 1000 words as the features of the vocabulary'''
newpass=[x[0] for x in sort_orders[:1000]]

''' Building a new dictionary that will be used to build a dataframe with the vocabulary features as the keys '''
newdict={}
print(newpass)

for x in newpass:
    newdict[x]=[]

['talk.politics.mideast', 'rec.autos', 'comp.sys.mac.hardware', 'alt.atheism', 'rec.sport.baseball', 'comp.os.ms-windows.misc', 'rec.sport.hockey', 'sci.crypt', 'sci.med', 'talk.politics.misc', 'rec.motorcycles', 'comp.windows.x', 'comp.graphics', 'comp.sys.ibm.pc.hardware', 'sci.electronics', 'talk.politics.guns', 'sci.space', 'soc.religion.christian', 'misc.forsale', 'talk.religion.misc']
1 Class done
2 Class done
3 Class done
4 Class done
5 Class done
6 Class done
7 Class done
8 Class done
9 Class done
10 Class done
11 Class done
12 Class done
13 Class done
14 Class done
15 Class done
16 Class done
17 Class done
18 Class done
19 Class done
20 Class done
['news', 'cantaloupe', 'message', 'subject', 'lines', 'date', 'newsgroups', 'path', 'organization', 'state', 'ohio', 'writes', 'article', 'comp', 'references', 'talk', 'misc', 'sender', 'howland', 'reston', 'people', 'like', 'just', 'university', 'posting', 'nntp', 'know', 'host', 'think', 'usenet', 'zaphod', 'politics', 'windows', '

In [4]:
newdict['Target']=[]

''' We repeat the process of going through each document again word by word, storing the frequency of words in the vocabulary'''

#storing the all the classe names in a list from the given folder
all_classes = os.listdir("20_newsgroups")

# Iterating through all classes
for class_ in all_classes:
    # storing the all documents in a list for a particular class
    all_docs = os.listdir("20_newsgroups"+"/"+class_)
    
    # traversing through all documents
    for docs in all_docs:
        
        # getting the base path which is common for all documents of a particular class
        path = "20_newsgroups"+"/"+class_+"/"+docs
        
        # opening the particular document as file object
        with open(path, encoding = "latin-1") as file_obj:
            newdict['Target'].append(class_)
            for x in newpass:
                newdict[x].append(0)
            
            # reading the document data
            file_data = file_obj.read()
            
            # stroing each words in a list , used re to remove the whitespaces 
            tokens = re.compile('\w+').findall(file_data)
            # traversing through all words and updating the value in dictionary if already exist otherwise will add to it
            for word in tokens:
                # checking if the word in a stop_word or not, is aphbetic and the lenth should be > 3 to avoid words like i, me etc
                if (word.lower() not in stop_words) and (word.lower().isalpha()) and (len(word.lower())>3) and (word.lower() in newpass):
                     newdict[word.lower()][-1]=newdict[word.lower()][-1]+1

In [5]:
''' Building a numpy 2-d array out of the X-dataframe'''
import pandas as pd
df = pd.DataFrame(newdict)
X=df.iloc[:,:-1].copy().to_numpy()
print(X)
''' Building a numpy 1-d array out of the Y-series(Target)'''
Y=df.iloc[:,-1].copy().to_numpy()
print(Y)

[[2 1 2 ... 0 0 0]
 [2 2 1 ... 0 0 0]
 [1 2 1 ... 0 0 0]
 ...
 [2 2 1 ... 0 0 0]
 [1 2 1 ... 0 0 0]
 [1 2 1 ... 0 0 0]]
['talk.politics.mideast' 'talk.politics.mideast' 'talk.politics.mideast'
 ... 'talk.religion.misc' 'talk.religion.misc' 'talk.religion.misc']


In [6]:
# Getting ready to use the in built Naive baiyes classifier:
## Train-Test splitting first:
from sklearn import model_selection
# Splitting the data into train - test, using random state to be 0 
X_train,X_test,Y_train,Y_test = model_selection.train_test_split(X,Y,test_size=0.25,random_state=0)
print(Y_test)

['comp.os.ms-windows.misc' 'comp.sys.ibm.pc.hardware' 'sci.space' ...
 'sci.space' 'talk.religion.misc' 'rec.motorcycles']


In [7]:
'''Using the in built MultinomialNaive Baiyes'''

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, confusion_matrix
# creating a classifier object
clf = MultinomialNB()

# fitting the classifier object to training data
clf.fit(X_train, Y_train)

# testing the classifier and storing the predicted Y_pred classes
Y_pred = clf.predict(X_test)
# Generating the classification report and printing the confusion matrix
print(classification_report(Y_test,Y_pred))
print(confusion_matrix(Y_test,Y_pred))

                          precision    recall  f1-score   support

             alt.atheism       0.80      0.72      0.76       240
           comp.graphics       0.88      0.74      0.81       244
 comp.os.ms-windows.misc       0.73      0.88      0.80       240
comp.sys.ibm.pc.hardware       0.69      0.68      0.68       256
   comp.sys.mac.hardware       0.68      0.73      0.71       249
          comp.windows.x       0.86      0.76      0.81       233
            misc.forsale       0.85      0.98      0.91       259
               rec.autos       0.83      0.86      0.85       253
         rec.motorcycles       0.82      0.94      0.88       231
      rec.sport.baseball       0.92      0.92      0.92       236
        rec.sport.hockey       0.91      0.95      0.93       261
               sci.crypt       0.98      0.93      0.95       269
         sci.electronics       0.84      0.89      0.87       246
                 sci.med       0.93      0.74      0.82       284
         

In [8]:

# Making a dictionary which will store the count of vocabulary words,,according to the different Y-target class values
grandy={}

# Declaring other helpful variables
df=None
sery=None
df1=None

## Writing my own naive baiyes::
# function used for fitting training data
def fit(X_train,Y_train):
    '''
    FUNCTION :
            fit : 
                Arguments : Training Data (X_train and Y_train)
        returns   : 
                A DICTIONARY :
                    Keys   : class_names and total count of all features
                    Values : DICTIONARY
                         Keys   : Words and total count of word of current_class
                         Values : number of times word appears in a sample of current_class 
    '''
    global df
    global df1
    global sery
    df = pd.DataFrame(data=X_train,columns=newpass)
    sery = pd.Series(Y_train)
    df1= pd.concat([df, sery], axis=1)
    unique_ys=sery.value_counts().index
    for x in unique_ys:
        grandy[x]=((df[df1[0]==x]).sum().to_dict())
        grandy[x]['Total']=((df[df1[0]==x]).sum()).sum()
fit(X_train,Y_train)
   

In [9]:
## Finding probability of test data belonging to a specific class:
import numpy as np
def prob_specific(dic,test,class_):
    log_prob=np.log(len(df[df1[0]==class_].index)/len(df.index))
    test_series=pd.Series(test)
    test_series.index=newpass
    for x in newpass:
        if test_series[x]==0:
            continue
        else:
            ## adding the log of probabilitiesusing laplace correction:
            log_prob+=np.log((dic[class_][x]+1)/(dic[class_]['Total']+len(newpass)))
    return log_prob

In [10]:
### Finding predicted class :
def predicted_class(dic,test):
    unique_ys=sery.value_counts().index
    curr_pred_clas=None
    curr_prob=-100000
    for x in unique_ys:
        if curr_prob<prob_specific(dic,test,x):
            curr_pred_clas=x
            curr_prob=prob_specific(dic,test,x)
    return curr_pred_clas
    

## Function used for predicting class of every test data point:
def predict_every(dic,Xtest):
    ypred=[]
    counter=0
    for x in Xtest:
        r=predicted_class(dic,x)
        ypred.append(r)
        counter+=1
        print(counter/len(Xtest)*100)
    return ypred

Y_pred=predict_every(grandy,X_test)

# generating the classification report and printing the confusion matrix
print(classification_report(Y_test,Y_pred))


    


0.02
0.04
0.06
0.08
0.1
0.12
0.13999999999999999
0.16
0.18
0.2
0.22
0.24
0.26
0.27999999999999997
0.3
0.32
0.33999999999999997
0.36
0.38
0.4
0.42
0.44
0.45999999999999996
0.48
0.5
0.52
0.54
0.5599999999999999
0.58
0.6
0.62
0.64
0.66
0.6799999999999999
0.7000000000000001
0.72
0.74
0.76
0.7799999999999999
0.8
0.8200000000000001
0.84
0.86
0.88
0.8999999999999999
0.9199999999999999
0.9400000000000001
0.96
0.98
1.0
1.02
1.04
1.06
1.08
1.0999999999999999
1.1199999999999999
1.1400000000000001
1.16
1.18
1.2
1.22
1.24
1.26
1.28
1.3
1.32
1.34
1.3599999999999999
1.38
1.4000000000000001
1.4200000000000002
1.44
1.46
1.48
1.5
1.52
1.54
1.5599999999999998
1.58
1.6
1.6199999999999999
1.6400000000000001
1.66
1.68
1.7000000000000002
1.72
1.7399999999999998
1.76
1.78
1.7999999999999998
1.82
1.8399999999999999
1.8599999999999999
1.8800000000000001
1.9
1.92
1.94
1.96
1.9800000000000002
2.0
2.02
2.04
2.06
2.08
2.1
2.12
2.1399999999999997
2.16
2.18
2.1999999999999997
2.22
2.2399999999999998
2.26
2.2800000000

18.22
18.240000000000002
18.26
18.279999999999998
18.3
18.32
18.34
18.360000000000003
18.38
18.4
18.42
18.44
18.459999999999997
18.48
18.5
18.52
18.54
18.56
18.58
18.6
18.62
18.64
18.66
18.68
18.7
18.72
18.740000000000002
18.759999999999998
18.78
18.8
18.82
18.84
18.86
18.88
18.9
18.92
18.94
18.96
18.98
19.0
19.02
19.040000000000003
19.06
19.08
19.1
19.12
19.139999999999997
19.16
19.18
19.2
19.220000000000002
19.24
19.259999999999998
19.28
19.3
19.32
19.34
19.36
19.38
19.400000000000002
19.42
19.439999999999998
19.46
19.48
19.5
19.52
19.54
19.56
19.580000000000002
19.6
19.62
19.64
19.66
19.68
19.7
19.72
19.74
19.759999999999998
19.78
19.8
19.82
19.84
19.86
19.88
19.900000000000002
19.919999999999998
19.939999999999998
19.96
19.98
20.0
20.02
20.04
20.06
20.080000000000002
20.1
20.119999999999997
20.14
20.16
20.18
20.200000000000003
20.22
20.24
20.26
20.28
20.3
20.32
20.34
20.36
20.380000000000003
20.4
20.419999999999998
20.44
20.46
20.48
20.5
20.52
20.54
20.560000000000002
20.5800000000

35.46
35.480000000000004
35.5
35.52
35.54
35.56
35.58
35.6
35.620000000000005
35.64
35.66
35.68
35.699999999999996
35.72
35.74
35.76
35.78
35.8
35.82
35.839999999999996
35.86
35.88
35.9
35.92
35.94
35.96
35.980000000000004
36.0
36.02
36.04
36.059999999999995
36.08
36.1
36.120000000000005
36.14
36.16
36.18
36.199999999999996
36.22
36.24
36.26
36.28
36.3
36.32
36.34
36.36
36.38
36.4
36.42
36.44
36.46
36.480000000000004
36.5
36.52
36.54
36.559999999999995
36.58
36.6
36.620000000000005
36.64
36.66
36.68
36.7
36.720000000000006
36.74
36.76
36.78
36.8
36.82
36.84
36.86
36.88
36.9
36.919999999999995
36.94
36.96
36.980000000000004
37.0
37.019999999999996
37.04
37.059999999999995
37.08
37.1
37.12
37.14
37.16
37.18
37.2
37.22
37.24
37.26
37.28
37.3
37.32
37.34
37.36
37.38
37.4
37.419999999999995
37.44
37.46
37.480000000000004
37.5
37.519999999999996
37.54
37.56
37.580000000000005
37.6
37.62
37.64
37.66
37.68
37.7
37.72
37.74
37.76
37.78
37.8
37.82
37.84
37.86
37.88
37.9
37.92
37.940000000000005


53.839999999999996
53.86
53.879999999999995
53.900000000000006
53.92
53.94
53.959999999999994
53.98
54.0
54.02
54.04
54.059999999999995
54.08
54.1
54.120000000000005
54.14
54.16
54.17999999999999
54.2
54.22
54.24
54.26
54.279999999999994
54.300000000000004
54.32
54.339999999999996
54.36
54.379999999999995
54.400000000000006
54.42
54.44
54.459999999999994
54.48
54.50000000000001
54.52
54.54
54.559999999999995
54.58
54.6
54.620000000000005
54.64
54.66
54.67999999999999
54.7
54.72
54.74
54.76
54.779999999999994
54.800000000000004
54.82
54.84
54.86
54.879999999999995
54.900000000000006
54.92
54.94
54.96
54.98
55.00000000000001
55.02
55.04
55.059999999999995
55.08
55.1
55.120000000000005
55.14
55.16
55.17999999999999
55.2
55.22
55.24
55.26
55.279999999999994
55.300000000000004
55.32
55.34
55.36
55.379999999999995
55.400000000000006
55.42
55.44
55.46
55.48
55.50000000000001
55.52
55.54
55.559999999999995
55.58
55.60000000000001
55.620000000000005
55.64
55.66
55.67999999999999
55.7
55.7200000

70.38
70.39999999999999
70.42
70.44
70.46
70.48
70.5
70.52000000000001
70.54
70.56
70.58
70.6
70.62
70.64
70.66
70.67999999999999
70.7
70.72
70.74000000000001
70.76
70.78
70.8
70.82000000000001
70.84
70.86
70.88
70.89999999999999
70.92
70.94
70.96000000000001
70.98
71.0
71.02000000000001
71.04
71.06
71.08
71.1
71.12
71.14
71.16
71.17999999999999
71.2
71.22
71.24000000000001
71.26
71.28
71.3
71.32
71.34
71.36
71.38
71.39999999999999
71.41999999999999
71.44
71.46000000000001
71.48
71.5
71.52
71.54
71.56
71.58
71.6
71.61999999999999
71.64
71.66
71.67999999999999
71.7
71.72
71.74000000000001
71.76
71.78
71.8
71.82
71.84
71.86
71.88
71.89999999999999
71.92
71.94
71.96000000000001
71.98
72.0
72.02
72.04
72.06
72.08
72.1
72.11999999999999
72.14
72.16
72.18
72.2
72.22
72.24000000000001
72.26
72.28
72.3
72.32
72.34
72.36
72.38
72.39999999999999
72.42
72.44
72.46000000000001
72.48
72.5
72.52
72.54
72.56
72.58
72.6
72.61999999999999
72.64
72.66
72.68
72.7
72.72
72.74000000000001
72.76
72.78
72.8


90.68
90.7
90.72
90.74
90.75999999999999
90.78
90.8
90.82000000000001
90.84
90.86
90.88000000000001
90.9
90.92
90.94
90.96
90.98
91.0
91.02
91.03999999999999
91.06
91.08000000000001
91.10000000000001
91.12
91.14
91.16
91.18
91.2
91.22
91.24
91.25999999999999
91.28
91.3
91.32000000000001
91.34
91.36
91.38
91.4
91.42
91.44
91.46
91.47999999999999
91.5
91.52
91.53999999999999
91.56
91.58
91.60000000000001
91.62
91.64
91.66
91.67999999999999
91.7
91.72
91.74
91.75999999999999
91.78
91.8
91.82000000000001
91.84
91.86
91.88
91.9
91.92
91.94
91.96
91.97999999999999
92.0
92.02
92.04
92.06
92.08
92.10000000000001
92.12
92.14
92.16
92.17999999999999
92.2
92.22
92.24
92.25999999999999
92.28
92.30000000000001
92.32000000000001
92.34
92.36
92.38
92.4
92.42
92.44
92.46
92.47999999999999
92.5
92.52
92.54
92.56
92.58
92.60000000000001
92.62
92.64
92.66
92.67999999999999
92.7
92.72
92.74
92.75999999999999
92.78
92.80000000000001
92.82000000000001
92.84
92.86
92.88
92.9
92.92
92.94
92.96
92.979999999999

In [11]:
print(confusion_matrix(Y_test,Y_pred))
##Overall comparison:
''' Both the cases perform well and the accuracy seems to be almost same in both cases of in buit naive bayes and self written naive baiyes as is evident
from the respective classification reports'''

[[192   1   0   0   0   0   0   0   9   1   0   0   0   4   0   0   0   0
    0  33]
 [  0 177  15  11  23   7   4   0   0   0   0   1   1   5   0   0   0   0
    0   0]
 [  0   4 206  13   6   8   1   1   0   0   0   0   1   0   0   0   0   0
    0   0]
 [  0   5   7 170  59   3   4   0   0   0   0   0   8   0   0   0   0   0
    0   0]
 [  0   2   2  44 188   1   7   0   0   0   0   0   5   0   0   0   0   0
    0   0]
 [  0  10  40   2   3 172   1   0   0   0   0   0   2   3   0   0   0   0
    0   0]
 [  0   0   1   2   4   0 244   4   0   0   0   0   3   1   0   0   0   0
    0   0]
 [  0   0   0   0   0   0   9 236   2   0   0   0   6   0   0   0   0   0
    0   0]
 [  0   0   0   0   0   0   2   3 222   0   0   0   0   1   2   0   1   0
    0   0]
 [  0   0   0   0   0   0   0   0   1 226   9   0   0   0   0   0   0   0
    0   0]
 [  0   0   0   0   0   0   0   0   0  11 249   0   0   1   0   0   0   0
    0   0]
 [  0   0   1   1   2   2   0   0   2   0   0 256   2   1   0   0

' Both the cases perform well and the accuracy seems to be almost same in both cases of in buit naive bayes and self written naive baiyes as is evident\nfrom the respective classification reports'